//! The `alfred` command-line surface.
//!
//! This module owns the top-level parser and the `job` subcommands added by
//! issue #15, plus the agent-facing capabilities added by issue #9: `todo`,
//! `webhook`, and `remember`. Each capability is paired with a `SKILL.md`
//! generated by [`crate::skills`].
//!
//! `job run` executes the job synchronously through the same
//! [`JobDispatch`](crate::jobs::dispatch::JobDispatch) composition the
//! scheduler installs, records the run row, delivers according to the job's
//! `report` policy, and prints the outcome and verdict.

use std::io::Write;
use std::path::Path;
use std::str::FromStr;
use std::sync::Arc;

use chrono::{DateTime, Utc};
use clap::{ArgGroup, Args, Parser, Subcommand, ValueEnum};

use crate::config::{load_config, JobsConfig};
use crate::error::AlfredError;
use crate::jobs::dispatch::JobDispatch;
use crate::jobs::runner::STATUS_SUCCESS;
use crate::jobs::{self, Job, JobKind, JobRun, NewJob, ReportPolicy};
use crate::memory;
use crate::scheduler::{run_to_completion, Dispatch};
use crate::store::Store;
use crate::webhook;

/// Default number of runs `alfred job runs` prints.
const DEFAULT_RUN_LIMIT: usize = 20;

/// Top-level command line.
#[derive(Parser, Debug)]
#[command(name = "alfred", about = "24x7 personal-assistant host", version = env!("CARGO_PKG_VERSION"))]
pub struct Cli {
    /// Path to config file
    #[arg(short, long, global = true)]
    pub config: Option<String>,
    /// Subcommand; with none, Alfred runs as the server.
    #[command(subcommand)]
    pub command: Option<CliCommand>,
}

#[derive(Subcommand, Debug)]
pub enum CliCommand {
    /// Manage jobs: add, list, show, enable, disable, run, runs, remove
    Job(JobArgs),
    /// Manage the user's todo list
    Todo(TodoArgs),
    /// Send an allow-listed outbound webhook
    Webhook(WebhookArgs),
    /// Append a durable fact to the user's memories file
    Remember(RememberArgs),
}

#[derive(Args, Debug)]
pub struct JobArgs {
    #[command(subcommand)]
    pub command: JobCommand,
}

#[derive(Subcommand, Debug)]
pub enum JobCommand {
    /// Create a job from exactly one of --cron, --at, or --watch
    Add(JobAddArgs),
    /// List all jobs
    List,
    /// Show one job by id or name
    Show {
        #[arg(value_name = "ID|NAME")]
        id_or_name: String,
    },
    /// Enable a job
    Enable {
        #[arg(value_name = "ID|NAME")]
        id_or_name: String,
    },
    /// Disable a job
    Disable {
        #[arg(value_name = "ID|NAME")]
        id_or_name: String,
    },
    /// Run a job now, synchronously
    Run {
        #[arg(value_name = "ID|NAME")]
        id_or_name: String,
    },
    /// Show a job's run history, newest first
    Runs {
        #[arg(value_name = "ID|NAME")]
        id_or_name: String,
        /// Maximum number of runs to print
        #[arg(long, default_value_t = DEFAULT_RUN_LIMIT)]
        limit: usize,
    },
    /// Delete a job and its run history
    Remove {
        #[arg(value_name = "ID|NAME")]
        id_or_name: String,
    },
}

/// The arguments of `alfred job add`.
#[derive(Args, Debug)]
#[command(group(
    ArgGroup::new("schedule")
        .required(true)
        .multiple(false)
        .args(["cron", "at", "watch"])
))]
pub struct JobAddArgs {
    /// Job name (unique)
    #[arg(long)]
    pub name: String,
    /// Prompt handed to the agent
    #[arg(long)]
    pub prompt: String,
    /// Recurring schedule: five-field cron, e.g. "0 9 * * *"
    #[arg(long)]
    pub cron: Option<String>,
    /// One-shot time: RFC 3339 or a relative offset such as "+5s", "+10m"
    #[arg(long)]
    pub at: Option<String>,
    /// Polling schedule: five-field cron, at least the configured interval
    #[arg(long)]
    pub watch: Option<String>,
    /// When to deliver the result: always or on_signal
    #[arg(long, default_value = "on_signal")]
    pub report: String,
    /// Delivery target, e.g. "telegram:42"
    #[arg(long = "deliver-to")]
    pub deliver_to: Option<String>,
    /// Model override
    #[arg(long)]
    pub model: Option<String>,
    /// Comma-separated tool allowlist
    #[arg(long)]
    pub tools: Option<String>,
    /// Per-run timeout in seconds
    #[arg(long, default_value_t = 900)]
    pub timeout: u64,
}

impl JobAddArgs {
    /// Build a [`NewJob`], parsing `--at` and the report/tool lists.
    fn to_new_job(&self) -> Result<NewJob, AlfredError> {
        let (kind, schedule, run_at) = if let Some(expression) = &self.cron {
            (JobKind::Recurring, Some(expression.clone()), None)
        } else if let Some(expression) = &self.watch {
            (JobKind::Watch, Some(expression.clone()), None)
        } else if let Some(at) = &self.at {
            (JobKind::Once, None, Some(parse_at(at)?))
        } else {
            return Err(AlfredError::JobValidation(
                "one of --cron, --at, or --watch is required".to_string(),
            ));
        };

        Ok(NewJob {
            name: self.name.clone(),
            kind,
            schedule,
            run_at,
            prompt: self.prompt.clone(),
            report: ReportPolicy::from_str(&self.report)?,
            deliver_to: self.deliver_to.clone(),
            model: self.model.clone(),
            tools: jobs::decode_tools(self.tools.clone()),
            timeout_secs: self.timeout,
        })
    }
}

// --------------------------------------------------------- todo, webhook, remember

/// Priority of a todo, highest first.
#[derive(Copy, Clone, Debug, PartialEq, Eq, ValueEnum)]
pub enum Priority {
    Low,
    Medium,
    High,
}

impl Priority {
    fn as_str(self) -> &'static str {
        match self {
            Priority::Low => "low",
            Priority::Medium => "medium",
            Priority::High => "high",
        }
    }
}

/// The arguments of `alfred todo`.
#[derive(Args, Debug)]
pub struct TodoArgs {
    #[command(subcommand)]
    pub command: TodoCommand,
}

#[derive(Subcommand, Debug)]
pub enum TodoCommand {
    /// Create a todo
    Add(TodoAddArgs),
    /// List open todos, highest priority first
    List,
    /// Mark a todo complete by id
    Complete {
        #[arg(value_name = "ID")]
        id: String,
    },
    /// Delete a todo by id
    Remove {
        #[arg(value_name = "ID")]
        id: String,
    },
}

/// The arguments of `alfred todo add`.
#[derive(Args, Debug)]
pub struct TodoAddArgs {
    /// Todo title
    #[arg(long)]
    pub title: String,
    /// Priority: low, medium, or high
    #[arg(long, value_enum, default_value = "medium")]
    pub priority: Priority,
    /// Optional longer description
    #[arg(long, default_value = "")]
    pub description: String,
    /// Optional free-form due date
    #[arg(long, default_value = "")]
    pub due: String,
}

/// The arguments of `alfred webhook`.
#[derive(Args, Debug)]
pub struct WebhookArgs {
    #[command(subcommand)]
    pub command: WebhookCommand,
}

#[derive(Subcommand, Debug)]
pub enum WebhookCommand {
    /// POST a JSON body to an allow-listed URL
    Send(WebhookSendArgs),
}

/// The arguments of `alfred webhook send`.
#[derive(Args, Debug)]
pub struct WebhookSendArgs {
    /// Absolute http(s) URL
    #[arg(value_name = "URL")]
    pub url: String,
    /// JSON request body
    #[arg(long, value_name = "JSON")]
    pub json: String,
}

/// The arguments of `alfred remember`.
#[derive(Args, Debug)]
pub struct RememberArgs {
    /// The fact to remember, as one line
    #[arg(value_name = "TEXT")]
    pub text: String,
}

/// Execute a parsed top-level command.
///
/// Errors are returned for the caller to print as `ERROR: <message>` on stderr.
pub async fn run(command: CliCommand, config_path: &str) -> Result<(), AlfredError> {
    match command {
        CliCommand::Job(args) => {
            let config = load_config(Path::new(config_path))?;
            // Resolve the database the same way the server does, so `job list`
            // sees what the server schedules and `ALFRED_DATA_DIR` isolates a
            // run. See `config::resolve_database_path` for the precedence.
            let store = Arc::new(Store::new(config.database_path().as_path())?);
            // Build the same composed dispatcher the server installs, so a
            // manual run and a scheduled run behave identically. `job run`
            // uses it; the other subcommands ignore it.
            let dispatch: Arc<dyn Dispatch> = Arc::new(JobDispatch::from_config(
                Arc::clone(&store),
                &config.pi,
                &config.jobs,
                config.telegram.as_ref(),
            ));
            let stdout = std::io::stdout();
            let mut out = stdout.lock();
            run_job(args.command, &store, &config.jobs, &dispatch, &mut out).await
        }
        CliCommand::Todo(args) => {
            // The todo store is the same database, so it must resolve through
            // the config too rather than the hard-coded home path.
            let config = load_config(Path::new(config_path))?;
            let store = Store::new(config.database_path().as_path())?;
            let stdout = std::io::stdout();
            let mut out = stdout.lock();
            run_todo(args.command, &store, &mut out)
        }
        CliCommand::Webhook(args) => {
            let config = load_config(Path::new(config_path))?;
            // `webhook::send` refuses a host off the allow-list before any
            // socket opens, so it never reaches Pi's raw `bash`.
            let output = run_webhook(args.command, &config.webhook.allowed_hosts).await?;
            let stdout = std::io::stdout();
            let mut out = stdout.lock();
            write!(out, "{output}")?;
            Ok(())
        }
        CliCommand::Remember(args) => {
            let text = args.text.trim();
            if text.is_empty() {
                return Err(AlfredError::Usage(
                    "remember needs a non-empty fact".to_string(),
                ));
            }
            memory::append_memory(text)?;
            let stdout = std::io::stdout();
            let mut out = stdout.lock();
            writeln!(out, "remembered")?;
            Ok(())
        }
    }
}

/// Run one `job` subcommand against `store`.
///
/// Split out from [`run`] so tests can supply a temporary database and an
/// injected dispatcher. `jobs` supplies the watch floor and the history bound;
/// `dispatch` is the composed runner + delivery used by `job run`.
pub async fn run_job(
    command: JobCommand,
    store: &Arc<Store>,
    jobs: &JobsConfig,
    dispatch: &Arc<dyn Dispatch>,
    out: &mut dyn Write,
) -> Result<(), AlfredError> {
    match command {
        JobCommand::Add(args) => {
            let new = args.to_new_job()?;
            let job = store.add_job(&new, jobs.min_watch_interval_secs)?;
            writeln!(out, "added job '{}' ({})", job.name, job.id)?;
            Ok(())
        }
        JobCommand::List => {
            let jobs = store.list_jobs()?;
            write_job_table(out, &jobs)
        }
        JobCommand::Show { id_or_name } => {
            let job = store.get_job(&id_or_name)?;
            write_job_detail(out, &job)
        }
        JobCommand::Enable { id_or_name } => {
            let job = store.set_enabled(&id_or_name, true)?;
            writeln!(out, "enabled job '{}' ({})", job.name, job.id)?;
            Ok(())
        }
        JobCommand::Disable { id_or_name } => {
            let job = store.set_enabled(&id_or_name, false)?;
            writeln!(out, "disabled job '{}' ({})", job.name, job.id)?;
            Ok(())
        }
        JobCommand::Run { id_or_name } => {
            let job = store.get_job(&id_or_name)?;
            let run = run_to_completion(store, dispatch, jobs.max_runs_per_job, &job).await?;
            write_run_outcome(out, &run)?;
            if run.status == STATUS_SUCCESS {
                Ok(())
            } else {
                // The run row is already written; surface a non-zero exit so a
                // failed manual run is not mistaken for a success by a script.
                Err(AlfredError::JobValidation(format!(
                    "job '{}' run {} ended '{}'",
                    job.name, run.id, run.status
                )))
            }
        }
        JobCommand::Runs { id_or_name, limit } => {
            let runs = store.runs_for(&id_or_name, limit)?;
            write_run_table(out, &runs)
        }
        JobCommand::Remove { id_or_name } => {
            let job = store.get_job(&id_or_name)?;
            store.delete_job(&job.id)?;
            writeln!(out, "removed job '{}' ({})", job.name, job.id)?;
            Ok(())
        }
    }
}

/// Run one `todo` subcommand against `store`.
pub fn run_todo(
    command: TodoCommand,
    store: &Store,
    out: &mut dyn Write,
) -> Result<(), AlfredError> {
    match command {
        TodoCommand::Add(args) => {
            let title = args.title.trim();
            if title.is_empty() {
                return Err(AlfredError::Usage(
                    "todo title must not be empty".to_string(),
                ));
            }
            let id = store.add_todo(
                title,
                args.description.trim(),
                args.priority.as_str(),
                args.due.trim(),
            )?;
            writeln!(out, "added todo {id}")?;
            Ok(())
        }
        TodoCommand::List => {
            let todos = store.list_todos()?;
            write_todo_table(out, &todos)
        }
        TodoCommand::Complete { id } => {
            if store.complete_todo(&id)? {
                writeln!(out, "completed todo {id}")?;
                Ok(())
            } else {
                Err(AlfredError::TodoNotFound(id))
            }
        }
        TodoCommand::Remove { id } => {
            if store.get_todo(&id)?.is_none() {
                return Err(AlfredError::TodoNotFound(id));
            }
            store.delete_todo(&id)?;
            writeln!(out, "removed todo {id}")?;
            Ok(())
        }
    }
}

/// Run one `webhook` subcommand and return the text to print.
///
/// Split out from [`run`] so tests can exercise the allow-list without a
/// terminal or the real `~/.alfred` directory.
pub async fn run_webhook(
    command: WebhookCommand,
    allowed_hosts: &[String],
) -> Result<String, AlfredError> {
    match command {
        WebhookCommand::Send(args) => {
            let body: serde_json::Value = serde_json::from_str(&args.json)
                .map_err(|error| AlfredError::Usage(format!("invalid --json body: {error}")))?;
            let response = webhook::send(&args.url, &body, allowed_hosts).await?;
            let mut output = format!("{} {}", response.status, args.url);
            if !response.body.is_empty() {
                output.push('\n');
                output.push_str(&response.body);
            }
            output.push('\n');
            Ok(output)
        }
    }
}

fn write_todo_table(out: &mut dyn Write, todos: &[crate::store::Todo]) -> Result<(), AlfredError> {
    writeln!(
        out,
        "{:<36}  {:<8}  {:<12}  {}",
        "ID", "PRIORITY", "DUE", "TITLE"
    )?;
    for todo in todos {
        writeln!(
            out,
            "{:<36}  {:<8}  {:<12}  {}",
            todo.id,
            todo.priority,
            todo.due_date.as_deref().unwrap_or("-"),
            todo.title
        )?;
    }
    Ok(())
}

/// Parse `--at`: an RFC 3339 timestamp, or a relative offset such as `+5s`,
/// `+10m`, `+2h`, `+1d` measured from now.
fn parse_at(value: &str) -> Result<i64, AlfredError> {
    let trimmed = value.trim();
    if let Some(rest) = trimmed.strip_prefix('+') {
        let (digits, unit) = split_duration(rest, value)?;
        let amount: i64 = digits.parse().map_err(|_| {
            AlfredError::JobValidation(format!(
                "invalid --at value '{value}': bad amount '{digits}'"
            ))
        })?;
        let multiplier: i64 = match unit {
            "s" => 1,
            "m" => 60,
            "h" => 3_600,
            "d" => 86_400,
            other => {
                return Err(AlfredError::JobValidation(format!(
                    "invalid --at value '{value}': unknown unit '{other}' (use s, m, h, or d)"
                )))
            }
        };
        let seconds = amount.checked_mul(multiplier).ok_or_else(|| {
            AlfredError::JobValidation(format!("invalid --at value '{value}': duration overflows"))
        })?;
        let now = Utc::now().timestamp();
        return now.checked_add(seconds).ok_or_else(|| {
            AlfredError::JobValidation(format!("invalid --at value '{value}': time overflows"))
        });
    }

    DateTime::parse_from_rfc3339(trimmed)
        .map(|time| time.timestamp())
        .map_err(|error| {
            AlfredError::JobValidation(format!("invalid --at value '{value}': {error}"))
        })
}

/// Split `5s` into (`5`, `s`), rejecting missing digits or a missing unit.
fn split_duration<'a>(rest: &'a str, original: &str) -> Result<(&'a str, &'a str), AlfredError> {
    let boundary = rest
        .find(|character: char| !character.is_ascii_digit())
        .unwrap_or(rest.len());
    let (digits, unit) = rest.split_at(boundary);
    if digits.is_empty() || unit.is_empty() {
        return Err(AlfredError::JobValidation(format!(
            "invalid --at value '{original}': expected a duration like +5s, +10m, +2h, or +1d"
        )));
    }
    Ok((digits, unit))
}

fn format_timestamp(timestamp: i64) -> String {
    DateTime::<Utc>::from_timestamp(timestamp, 0)
        .map(|time| time.format("%Y-%m-%dT%H:%M:%SZ").to_string())
        .unwrap_or_else(|| timestamp.to_string())
}

fn format_timestamp_opt(timestamp: Option<i64>) -> String {
    timestamp
        .map(format_timestamp)
        .unwrap_or_else(|| "-".to_string())
}

fn format_tokens(input: Option<i64>, output: Option<i64>) -> String {
    match (input, output) {
        (None, None) => "-".to_string(),
        (input, output) => format!(
            "{}/{}",
            input
                .map(|v| v.to_string())
                .unwrap_or_else(|| "-".to_string()),
            output
                .map(|v| v.to_string())
                .unwrap_or_else(|| "-".to_string())
        ),
    }
}

fn write_job_table(out: &mut dyn Write, jobs: &[Job]) -> Result<(), AlfredError> {
    writeln!(
        out,
        "{:<36}  {:<20}  {:<9}  {:<16}  {:<7}  {}",
        "ID", "NAME", "KIND", "SCHEDULE", "ENABLED", "LAST_STATUS"
    )?;
    for job in jobs {
        writeln!(
            out,
            "{:<36}  {:<20}  {:<9}  {:<16}  {:<7}  {}",
            job.id,
            job.name,
            job.kind.as_str(),
            job.schedule.as_deref().unwrap_or("-"),
            if job.enabled { "yes" } else { "no" },
            job.last_status.as_deref().unwrap_or("-")
        )?;
    }
    Ok(())
}

fn write_job_detail(out: &mut dyn Write, job: &Job) -> Result<(), AlfredError> {
    writeln!(out, "id:          {}", job.id)?;
    writeln!(out, "name:        {}", job.name)?;
    writeln!(out, "kind:        {}", job.kind.as_str())?;
    writeln!(
        out,
        "schedule:    {}",
        job.schedule.as_deref().unwrap_or("-")
    )?;
    writeln!(out, "run_at:      {}", format_timestamp_opt(job.run_at))?;
    writeln!(out, "prompt:      {}", job.prompt)?;
    writeln!(out, "report:      {}", job.report.as_str())?;
    writeln!(
        out,
        "deliver_to:  {}",
        job.deliver_to.as_deref().unwrap_or("-")
    )?;
    writeln!(out, "model:       {}", job.model.as_deref().unwrap_or("-"))?;
    writeln!(
        out,
        "tools:       {}",
        if job.tools.is_empty() {
            "-".to_string()
        } else {
            job.tools.join(",")
        }
    )?;
    writeln!(out, "timeout:     {}s", job.timeout_secs)?;
    writeln!(
        out,
        "enabled:     {}",
        if job.enabled { "yes" } else { "no" }
    )?;
    writeln!(out, "last_run:    {}", format_timestamp_opt(job.last_run))?;
    writeln!(
        out,
        "last_status: {}",
        job.last_status.as_deref().unwrap_or("-")
    )?;
    writeln!(out, "created_at:  {}", format_timestamp(job.created_at))?;
    writeln!(out, "updated_at:  {}", format_timestamp(job.updated_at))?;
    Ok(())
}

/// Print the outcome and verdict of one manual run.
fn write_run_outcome(out: &mut dyn Write, run: &JobRun) -> Result<(), AlfredError> {
    writeln!(out, "run:        {}", run.id)?;
    writeln!(out, "status:     {}", run.status)?;
    writeln!(
        out,
        "verdict:    {}",
        run.verdict.as_deref().unwrap_or("-")
    )?;
    writeln!(
        out,
        "delivered:  {}",
        if run.delivered { "yes" } else { "no" }
    )?;
    if let Some(error) = run.error.as_deref() {
        writeln!(out, "error:      {error}")?;
    }
    if let Some(output) = run.output.as_deref() {
        writeln!(out, "output:     {output}")?;
    }
    Ok(())
}

fn write_run_table(out: &mut dyn Write, runs: &[JobRun]) -> Result<(), AlfredError> {
    writeln!(
        out,
        "{:<20}  {:<20}  {:<10}  {:<10}  {:<9}  {:<10}  {}",
        "STARTED_AT", "FINISHED_AT", "STATUS", "VERDICT", "DELIVERED", "COST_USD", "TOKENS"
    )?;
    for run in runs {
        writeln!(
            out,
            "{:<20}  {:<20}  {:<10}  {:<10}  {:<9}  {:<10}  {}",
            format_timestamp(run.started_at),
            format_timestamp_opt(run.finished_at),
            run.status,
            run.verdict.as_deref().unwrap_or("-"),
            if run.delivered { "yes" } else { "no" },
            run.cost_usd
                .map(|cost| format!("{cost:.4}"))
                .unwrap_or_else(|| "-".to_string()),
            format_tokens(run.tokens_input, run.tokens_output)
        )?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use clap::Parser;

    fn store() -> (tempfile::TempDir, Arc<Store>) {
        let dir = tempfile::tempdir().expect("tempdir");
        let store = Arc::new(Store::new(&dir.path().join("jobs.db")).expect("open store"));
        (dir, store)
    }

    /// A dispatcher the CRUD subcommands never reach.
    fn inert_dispatch(store: &Arc<Store>) -> Arc<dyn Dispatch> {
        Arc::new(JobDispatch::from_config(
            Arc::clone(store),
            &crate::config::PiConfig::default(),
            &JobsConfig::default(),
            None,
        ))
    }

    async fn run_with(
        command: JobCommand,
        store: &Arc<Store>,
        dispatch: &Arc<dyn Dispatch>,
    ) -> Result<String, AlfredError> {
        let mut buffer = Vec::new();
        run_job(command, store, &JobsConfig::default(), dispatch, &mut buffer).await?;
        String::from_utf8(buffer).map_err(|error| AlfredError::JobValidation(error.to_string()))
    }

    async fn run(command: JobCommand, store: &Arc<Store>) -> Result<String, AlfredError> {
        let dispatch = inert_dispatch(store);
        run_with(command, store, &dispatch).await
    }

    fn add_args(name: &str, prompt: &str) -> JobAddArgs {
        JobAddArgs {
            name: name.to_string(),
            prompt: prompt.to_string(),
            cron: None,
            at: Some("+5s".to_string()),
            watch: None,
            report: "always".to_string(),
            deliver_to: None,
            model: None,
            tools: None,
            timeout: 900,
        }
    }

    #[tokio::test]
    async fn add_list_show_and_remove_round_trip() {
        let (_dir, store) = store();

        let added = run(JobCommand::Add(add_args("probe", "hello")), &store)
            .await
            .expect("add");
        assert!(added.contains("probe"), "output was: {added}");

        let listed = run(JobCommand::List, &store).await.expect("list");
        assert!(listed.contains("probe"), "output was: {listed}");
        assert!(listed.contains("once"), "output was: {listed}");

        let shown = run(
            JobCommand::Show {
                id_or_name: "probe".to_string(),
            },
            &store,
        )
        .await
        .expect("show");
        assert!(shown.contains("hello"), "output was: {shown}");
        assert!(shown.contains("report:      always"), "output was: {shown}");

        let removed = run(
            JobCommand::Remove {
                id_or_name: "probe".to_string(),
            },
            &store,
        )
        .await
        .expect("remove");
        assert!(removed.contains("removed"), "output was: {removed}");
        assert!(store.get_job("probe").is_err(), "job should be gone");
    }

    #[tokio::test]
    async fn watch_below_minimum_reports_the_exact_message() {
        let (_dir, store) = store();
        let mut args = add_args("w", "x");
        args.at = None;
        args.watch = Some("*/1 * * * *".to_string());

        let error = run(JobCommand::Add(args), &store)
            .await
            .expect_err("watch must fail");
        assert_eq!(error.to_string(), "minimum watch interval is 900s");
    }

    #[tokio::test]
    async fn enable_and_disable_flip_the_stored_flag() {
        let (_dir, store) = store();
        run(JobCommand::Add(add_args("probe", "hello")), &store)
            .await
            .expect("add");

        run(
            JobCommand::Disable {
                id_or_name: "probe".to_string(),
            },
            &store,
        )
        .await
        .expect("disable");
        assert!(!store.get_job("probe").expect("get").enabled);

        run(
            JobCommand::Enable {
                id_or_name: "probe".to_string(),
            },
            &store,
        )
        .await
        .expect("enable");
        assert!(store.get_job("probe").expect("get").enabled);
    }

    #[tokio::test]
    async fn runs_with_no_history_still_prints_the_header_row() {
        let (_dir, store) = store();
        run(JobCommand::Add(add_args("probe", "hello")), &store)
            .await
            .expect("add");

        let output = run(
            JobCommand::Runs {
                id_or_name: "probe".to_string(),
                limit: 20,
            },
            &store,
        )
        .await
        .expect("runs");
        assert!(output.contains("STARTED_AT"), "output was: {output}");
    }

    #[tokio::test]
    async fn run_of_an_unknown_job_is_not_found_and_records_nothing() {
        let (_dir, store) = store();
        let dispatch = inert_dispatch(&store);

        let error = run_with(
            JobCommand::Run {
                id_or_name: "missing".to_string(),
            },
            &store,
            &dispatch,
        )
        .await
        .expect_err("an unknown job must fail before any run");
        assert!(
            matches!(error, AlfredError::JobNotFound(_)),
            "error was: {error}"
        );
    }

    #[tokio::test]
    async fn tools_flag_splits_on_commas() {
        let (_dir, store) = store();
        let mut args = add_args("probe", "hello");
        args.tools = Some("bash, todo".to_string());
        run(JobCommand::Add(args), &store).await.expect("add");

        assert_eq!(
            store.get_job("probe").expect("get").tools,
            vec!["bash".to_string(), "todo".to_string()]
        );
    }

    #[test]
    fn relative_at_is_about_now_plus_the_offset() {
        let before = Utc::now().timestamp();
        let at = parse_at("+5s").expect("relative");
        let after = Utc::now().timestamp();
        assert!(at >= before + 5 && at <= after + 5, "at was {at}");
    }

    #[test]
    fn rfc3339_at_is_parsed() {
        let expected = DateTime::parse_from_rfc3339("2026-01-02T03:04:05Z")
            .expect("fixture")
            .timestamp();
        assert_eq!(parse_at("2026-01-02T03:04:05Z").expect("rfc3339"), expected);
    }

    #[test]
    fn malformed_at_is_rejected() {
        assert!(parse_at("+5x").is_err());
        assert!(parse_at("+h").is_err());
        assert!(parse_at("not-a-date").is_err());
    }

    #[test]
    fn clap_requires_exactly_one_schedule_flag() {
        assert!(
            Cli::try_parse_from(["alfred", "job", "add", "--name", "n", "--prompt", "p"]).is_err()
        );
        assert!(Cli::try_parse_from([
            "alfred",
            "job",
            "add",
            "--name",
            "n",
            "--prompt",
            "p",
            "--at",
            "+5s",
            "--watch",
            "*/5 * * * *",
        ])
        .is_err());
        assert!(Cli::try_parse_from([
            "alfred", "job", "add", "--name", "n", "--prompt", "p", "--at", "+5s",
        ])
        .is_ok());
    }

    // ----------------------------------------------------- todo, webhook, remember

    fn todo(command: TodoCommand, store: &Store) -> Result<String, AlfredError> {
        let mut buffer = Vec::new();
        run_todo(command, store, &mut buffer)?;
        String::from_utf8(buffer).map_err(|error| AlfredError::Usage(error.to_string()))
    }

    fn todo_add_args(title: &str, priority: Priority) -> TodoAddArgs {
        TodoAddArgs {
            title: title.to_string(),
            priority,
            description: String::new(),
            due: String::new(),
        }
    }

    fn added_id(output: &str) -> String {
        output
            .trim()
            .strip_prefix("added todo ")
            .expect("add output starts with 'added todo '")
            .to_string()
    }

    #[test]
    fn todo_add_list_complete_remove_round_trip() {
        let (_dir, store) = store();

        let added = todo(
            TodoCommand::Add(todo_add_args("probe", Priority::Low)),
            &store,
        )
        .expect("add");
        let id = added_id(&added);

        let listed = todo(TodoCommand::List, &store).expect("list");
        assert!(listed.contains("probe"), "output was: {listed}");
        assert!(listed.contains("low"), "output was: {listed}");
        assert!(listed.contains(&id), "output was: {listed}");

        let completed = todo(TodoCommand::Complete { id: id.clone() }, &store).expect("complete");
        assert!(
            completed.contains("completed todo"),
            "output was: {completed}"
        );
        let listed = todo(TodoCommand::List, &store).expect("list");
        assert!(
            !listed.contains("probe"),
            "completed todos are hidden: {listed}"
        );

        let second = todo(
            TodoCommand::Add(todo_add_args("remove me", Priority::High)),
            &store,
        )
        .expect("add");
        let second_id = added_id(&second);
        let removed = todo(TodoCommand::Remove { id: second_id }, &store).expect("remove");
        assert!(removed.contains("removed todo"), "output was: {removed}");
        assert!(!todo(TodoCommand::List, &store)
            .expect("list")
            .contains("remove me"));
    }

    #[test]
    fn completing_or_removing_an_unknown_todo_is_a_typed_error() {
        let (_dir, store) = store();

        let error = todo(TodoCommand::Complete { id: "nope".into() }, &store)
            .expect_err("complete must fail");
        assert_eq!(error.to_string(), "todo not found: nope");

        let error =
            todo(TodoCommand::Remove { id: "nope".into() }, &store).expect_err("remove must fail");
        assert_eq!(error.to_string(), "todo not found: nope");
    }

    #[test]
    fn empty_todo_title_is_rejected() {
        let (_dir, store) = store();
        let error = todo(
            TodoCommand::Add(todo_add_args("   ", Priority::Medium)),
            &store,
        )
        .expect_err("blank title must fail");
        assert_eq!(error.to_string(), "todo title must not be empty");
    }

    #[test]
    fn clap_parses_the_agent_facing_commands() {
        let cli = Cli::try_parse_from([
            "alfred",
            "todo",
            "add",
            "--title",
            "probe",
            "--priority",
            "low",
        ])
        .expect("todo add parses");
        match cli.command {
            Some(CliCommand::Todo(TodoArgs {
                command: TodoCommand::Add(args),
            })) => {
                assert_eq!(args.title, "probe");
                assert_eq!(args.priority, Priority::Low);
            }
            other => panic!("unexpected parse: {other:?}"),
        }

        assert!(
            Cli::try_parse_from([
                "alfred",
                "todo",
                "add",
                "--title",
                "t",
                "--priority",
                "urgent"
            ])
            .is_err(),
            "an unknown priority must be rejected"
        );
        assert!(Cli::try_parse_from(["alfred", "remember", "test memory"]).is_ok());
        assert!(Cli::try_parse_from([
            "alfred",
            "webhook",
            "send",
            "https://example.com/x",
            "--json",
            "{}",
        ])
        .is_ok());
    }

    #[tokio::test]
    async fn webhook_send_refuses_a_host_off_the_allow_list() {
        let command = WebhookCommand::Send(WebhookSendArgs {
            url: "https://example.com/x".to_string(),
            json: "{}".to_string(),
        });
        let error = run_webhook(command, &[]).await.expect_err("must refuse");
        assert_eq!(error.to_string(), "host not allowed: example.com");
    }

    #[tokio::test]
    async fn webhook_send_rejects_an_invalid_json_body() {
        let command = WebhookCommand::Send(WebhookSendArgs {
            url: "https://example.com/x".to_string(),
            json: "not json".to_string(),
        });
        let error = run_webhook(command, &["example.com".to_string()])
            .await
            .expect_err("invalid json must fail");
        assert!(
            error.to_string().contains("invalid --json body"),
            "message was: {error}"
        );
    }
}
